version: '3.7'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    command: elasticsearch -Enetwork.host=_local_,_site_ -Enetwork.publish_host=_local_
    environment:
    - cluster.name=eslocal
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./kibana:/usr/share/kibana/config/kibana
    restart: on-failure
    depends_on:
      - elasticsearch
    
  twitter-go:
    build: twitter-go
    container_name: twitter-go
    volumes:
      - ./twitter-go:/app
    restart: on-failure
    depends_on:
      - elasticsearch